env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: "es2017"
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "@typescript-eslint/no-explicit-any": "off",
  "no-undef": "off",
  "@typescript-eslint/no-var-requires": "off"
}
